version: '3.3'
services:
  jenkins:
      image: jenkins/jenkins:lts
      restart: unless-stopped
      privileged: true
      ports:
        - 8080:8080
      container_name: jenkins
      volumes:
        - ~/jenkins:/var/jenkins_home
